import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'
import { publishablePackages } from './publishablePackages'

// Each package's docusaurus-plugin-typedoc instance generates a single
// docs/api/<pkg>/index.md (outputFileStrategy: 'modules' over a one-file
// package → one page with every export). We reference those pages directly
// rather than the plugin's autogenerated sidebar, which is empty for a
// single-module entry point.
const sidebars: SidebarsConfig = {
	docs: [
		{
			type: 'category',
			label: 'Start here',
			collapsed: false,
			items: ['index', 'guides/installation'],
		},
		{
			type: 'category',
			label: 'Packages',
			collapsed: false,
			items: [
				'guides/api-errors',
				'guides/api-auth',
				'guides/api-config',
				'guides/api-logger',
				'guides/api-response',
				'guides/api-validation',
				'guides/api-rate-limit',
				'guides/api-health',
				'guides/api-http',
				'guides/api-amqp',
				'guides/api-openapi',
				'guides/custom-errors',
				'guides/testing',
			],
		},
		{
			type: 'category',
			label: 'Middleware',
			collapsed: false,
			items: [
				'guides/express',
				'guides/hono',
				'guides/api-auth-express',
				'guides/api-auth-hono',
				'guides/api-cors-express',
				'guides/api-express-utils',
				'guides/api-upload',
				'guides/api-openapi-express',
				'guides/api-openapi-hono',
				'guides/api-ts-rest-express',
				'guides/api-rate-limit-express',
				'guides/api-rate-limit-hono',
				'guides/api-health-express',
				'guides/api-health-hono',
			],
		},
		{
			type: 'category',
			label: 'API Reference',
			collapsed: false,
			// Derived from the workspace (same source as the typedoc instances)
			// so every publishable package has a reference page automatically.
			items: publishablePackages.map((pkg) => ({
				type: 'doc' as const,
				id: `api/${pkg}/index`,
				label: pkg,
			})),
		},
		{
			type: 'category',
			label: 'Examples',
			collapsed: false,
			items: ['examples/express', 'examples/hono', 'examples/auth'],
		},
		{
			type: 'category',
			label: 'Releases',
			items: ['changelog'],
		},
	],
}

export default sidebars
