import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'
import { publishablePackages } from './publishablePackages'

// Each package's docusaurus-plugin-typedoc instance generates a single
// docs/api/<pkg>/index.md (outputFileStrategy: 'modules' over a one-file
// package → one page with every export). We reference those pages directly
// rather than the plugin's autogenerated sidebar, which is empty for a
// single-module entry point.
const sidebars: SidebarsConfig = {
	docs: [
		{
			type: 'category',
			label: 'Start here',
			collapsed: false,
			items: ['index', 'guides/installation'],
		},
		{
			type: 'category',
			label: 'Packages',
			collapsed: false,
			items: [
				'guides/api-errors',
				'guides/api-auth',
				'guides/api-config',
				'guides/api-logger',
				'guides/api-response',
				'guides/api-validation',
				'guides/api-rate-limit',
				'guides/api-timeout',
				'guides/api-health',
				'guides/api-graceful-shutdown',
				'guides/api-http',
				'guides/api-amqp',
				'guides/api-openapi',
				'guides/api-webhooks',
				'guides/api-mcp',
				'guides/custom-errors',
				'guides/testing',
			],
		},
		{
			type: 'category',
			label: 'Middleware',
			collapsed: false,
			items: [
				'guides/express',
				'guides/hono',
				'guides/api-auth-express',
				'guides/api-auth-hono',
				'guides/api-cors-express',
				'guides/api-security-express',
				'guides/api-express-utils',
				'guides/api-upload',
				'guides/api-upload-hono',
				'guides/api-openapi-express',
				'guides/api-openapi-hono',
				'guides/api-ts-rest-express',
				'guides/api-rate-limit-express',
				'guides/api-rate-limit-hono',
				'guides/api-timeout-express',
				'guides/api-timeout-hono',
				'guides/api-health-express',
				'guides/api-health-hono',
				'guides/api-webhooks-express',
				'guides/api-webhooks-hono',
			],
		},
		{
			type: 'category',
			label: 'API Reference',
			collapsed: false,
			// Landing page at /docs/api (the nav "API" link) — auto-lists every
			// package page as a card, nothing to hand-maintain.
			link: {
				type: 'generated-index',
				title: 'API Reference',
				description:
					'TypeDoc reference for every published @rtorcato/api-* package. Pick a package below.',
				slug: '/api',
			},
			// Derived from the workspace (same source as the typedoc instances)
			// so every publishable package has a reference page automatically.
			items: publishablePackages.map((pkg) => ({
				type: 'doc' as const,
				id: `api/${pkg}/index`,
				label: pkg,
			})),
		},
		{
			type: 'category',
			label: 'Examples',
			collapsed: false,
			// Landing page at /docs/examples (the nav "Examples" link).
			link: {
				type: 'generated-index',
				title: 'Examples',
				description: 'Runnable apps that wire the api-common packages together end to end.',
				slug: '/examples',
			},
			items: [
				'examples/express',
				'examples/hono',
				'examples/ts-rest-express',
				'examples/amqp-worker',
				'examples/mcp',
				'examples/auth',
			],
		},
		{
			type: 'category',
			label: 'Releases',
			items: ['changelog'],
		},
	],
}

export default sidebars
