import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// Each package's docusaurus-plugin-typedoc instance generates a single
// docs/api/<pkg>/index.md (outputFileStrategy: 'modules' over a one-file
// package → one page with every export). We reference those pages directly
// rather than the plugin's autogenerated sidebar, which is empty for a
// single-module entry point.
const sidebars: SidebarsConfig = {
	docs: [
		{
			type: 'category',
			label: 'Start here',
			collapsed: false,
			items: ['index', 'guides/installation', 'guides/express', 'guides/hono'],
		},
		{
			type: 'category',
			label: 'Packages',
			collapsed: false,
			items: [
				'guides/api-errors',
				'guides/api-config',
				'guides/api-logger',
				'guides/api-response',
				'guides/api-validation',
				'guides/api-rate-limit',
				'guides/custom-errors',
				'guides/testing',
			],
		},
		{
			type: 'category',
			label: 'API Reference',
			collapsed: false,
			items: [
				{ type: 'doc', id: 'api/api-errors/index', label: 'api-errors' },
				{ type: 'doc', id: 'api/api-errors-express/index', label: 'api-errors-express' },
				{ type: 'doc', id: 'api/api-errors-hono/index', label: 'api-errors-hono' },
			],
		},
		{
			type: 'category',
			label: 'Examples',
			collapsed: false,
			items: ['examples/express', 'examples/hono', 'examples/auth'],
		},
		{
			type: 'category',
			label: 'Releases',
			items: ['changelog'],
		},
	],
}

export default sidebars
